/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import java.awt.*;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author ACER
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    private AuthController auth;
    private NavigationController nav;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        nav = new NavigationController(mainCardPanel);
        auth = new AuthController(nav);
        
    
    // Show login first
    nav.show("card6");
    }
    
    public NavigationController getNavigation()
    {
        return nav;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCardPanel = new javax.swing.JPanel();
        AuthPanel = new javax.swing.JPanel();
        authCardPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LoginCombo = new javax.swing.JComboBox<>();
        LoginUsername = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LoginImg = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RegisterUsername = new javax.swing.JTextField();
        RegisterPassword = new javax.swing.JTextField();
        RegisterName = new javax.swing.JTextField();
        RegisterContact = new javax.swing.JTextField();
        RegisterAddress = new javax.swing.JTextField();
        RegisterEmail = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LoginImg1 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnManageFarmers = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        ContentArea = new javax.swing.JPanel();
        ManageOrder = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        ProductName = new javax.swing.JTextField();
        comboCategory = new javax.swing.JComboBox<>();
        Brand = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        buttonSave = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        FarmerPanel = new javax.swing.JPanel();
        FarmerSideBar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        FarmerContentArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainCardPanel.setBackground(new java.awt.Color(245, 247, 250));
        mainCardPanel.setLayout(new java.awt.CardLayout());

        AuthPanel.setBackground(new java.awt.Color(245, 247, 250));
        AuthPanel.setLayout(new java.awt.BorderLayout());

        authCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        authCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        authCardPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        authCardPanel.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        LoginPanel.setRequestFocusEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FarmHub Login");

        LoginCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Farmer" }));
        LoginCombo.setPreferredSize(new java.awt.Dimension(250, 35));

        LoginUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginUsername.setText("Enter Username");
        LoginUsername.setPreferredSize(new java.awt.Dimension(250, 35));

        LoginPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginPassword.setText("jPasswordField1");
        LoginPassword.setPreferredSize(new java.awt.Dimension(250, 35));

        jButton1.setBackground(new java.awt.Color(46, 125, 50));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(250, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 101, 192));
        jLabel1.setText("Register as Farmer");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        LoginImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/loginimg.jpg"))); // NOI18N
        LoginImg.setText("jLabel6");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LoginCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LoginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))))
                .addGap(18, 18, 18)
                .addComponent(LoginImg, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginImg)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(LoginCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        authCardPanel.add(LoginPanel, "card2");

        RegisterPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisterPanel.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Farmer Registration");

        RegisterUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterUsername.setText("Username");
        RegisterUsername.setPreferredSize(new java.awt.Dimension(250, 35));
        RegisterUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUsernameActionPerformed(evt);
            }
        });

        RegisterPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterPassword.setText("Password");
        RegisterPassword.setPreferredSize(new java.awt.Dimension(250, 35));

        RegisterName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterName.setText("Full Name");
        RegisterName.setPreferredSize(new java.awt.Dimension(250, 35));

        RegisterContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterContact.setText("Contact");
        RegisterContact.setPreferredSize(new java.awt.Dimension(250, 35));

        RegisterAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterAddress.setText("Address");
        RegisterAddress.setPreferredSize(new java.awt.Dimension(250, 35));

        RegisterEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterEmail.setText("Email");
        RegisterEmail.setPreferredSize(new java.awt.Dimension(250, 35));

        RegisterButton.setBackground(new java.awt.Color(46, 125, 50));
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.setPreferredSize(new java.awt.Dimension(250, 40));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton2.setText("Back to Login");
        jButton2.setPreferredSize(new java.awt.Dimension(250, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LoginImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/loginimg.jpg"))); // NOI18N
        LoginImg1.setText("jLabel6");

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addComponent(LoginImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginImg1)
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        authCardPanel.add(RegisterPanel, "card3");

        AuthPanel.add(authCardPanel, java.awt.BorderLayout.CENTER);

        mainCardPanel.add(AuthPanel, "card6");

        AdminPanel.setLayout(new java.awt.BorderLayout());

        SideBar.setBackground(new java.awt.Color(0, 51, 0));
        SideBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        SideBar.setPreferredSize(new java.awt.Dimension(240, 720));
        SideBar.setLayout(new java.awt.GridLayout(10, 0, 1, 10));

        jLabel4.setBackground(new java.awt.Color(0, 51, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN");
        SideBar.add(jLabel4);

        btnManageFarmers.setBackground(new java.awt.Color(51, 102, 0));
        btnManageFarmers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManageFarmers.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFarmers.setText("Manage Farmers");
        btnManageFarmers.setBorderPainted(false);
        btnManageFarmers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageFarmers.setFocusPainted(false);
        btnManageFarmers.setPreferredSize(new java.awt.Dimension(200, 42));
        btnManageFarmers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFarmersActionPerformed(evt);
            }
        });
        SideBar.add(btnManageFarmers);

        jButton5.setBackground(new java.awt.Color(51, 102, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Manage Products");
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setPreferredSize(new java.awt.Dimension(200, 42));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        SideBar.add(jButton5);

        jButton6.setBackground(new java.awt.Color(51, 102, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View Reports");
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setPreferredSize(new java.awt.Dimension(200, 42));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        SideBar.add(jButton6);

        jButton7.setBackground(new java.awt.Color(51, 102, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Logout");
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setPreferredSize(new java.awt.Dimension(200, 42));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        SideBar.add(jButton7);

        AdminPanel.add(SideBar, java.awt.BorderLayout.LINE_START);

        ContentArea.setBackground(new java.awt.Color(255, 255, 204));
        ContentArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        ContentArea.setLayout(new java.awt.CardLayout());

        ManageOrder.setBackground(new java.awt.Color(255, 255, 204));

        Title.setBackground(new java.awt.Color(255, 255, 204));
        Title.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("Add new Tool/Pesticides");

        ProductName.setText("Product Name");
        ProductName.setPreferredSize(new java.awt.Dimension(210, 40));

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tool", "Pesticide" }));
        comboCategory.setPreferredSize(new java.awt.Dimension(210, 40));

        Brand.setText("Brand");
        Brand.setPreferredSize(new java.awt.Dimension(210, 40));
        Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandActionPerformed(evt);
            }
        });

        Price.setText("Price");
        Price.setPreferredSize(new java.awt.Dimension(210, 40));
        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });

        Quantity.setText("Quantity");

        Description.setColumns(20);
        Description.setRows(5);
        Description.setText("Description");
        jScrollPane1.setViewportView(Description);

        buttonSave.setBackground(new java.awt.Color(51, 153, 0));
        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonClear.setBackground(new java.awt.Color(204, 51, 0));
        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Tool", "Brand", "Price", "Quantity", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setText("Delete Product");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageOrderLayout = new javax.swing.GroupLayout(ManageOrder);
        ManageOrder.setLayout(ManageOrderLayout);
        ManageOrderLayout.setHorizontalGroup(
            ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ManageOrderLayout.createSequentialGroup()
                        .addGroup(ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(Brand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(Quantity, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ManageOrderLayout.setVerticalGroup(
            ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageOrderLayout.createSequentialGroup()
                .addGroup(ManageOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManageOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManageOrderLayout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(36, 36, 36)
                        .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        ContentArea.add(ManageOrder, "card2");

        AdminPanel.add(ContentArea, java.awt.BorderLayout.CENTER);

        mainCardPanel.add(AdminPanel, "card3");

        FarmerPanel.setLayout(new java.awt.BorderLayout());

        FarmerSideBar.setBackground(new java.awt.Color(0, 51, 0));
        FarmerSideBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        FarmerSideBar.setPreferredSize(new java.awt.Dimension(240, 720));
        FarmerSideBar.setLayout(new java.awt.GridLayout(10, 0, 1, 10));

        jLabel5.setBackground(new java.awt.Color(0, 51, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FARMER");
        FarmerSideBar.add(jLabel5);

        jButton3.setBackground(new java.awt.Color(51, 102, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Farming Techniques");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(200, 42));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        FarmerSideBar.add(jButton3);

        jButton8.setBackground(new java.awt.Color(51, 102, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Buy Tools & Pesticides");
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.setPreferredSize(new java.awt.Dimension(200, 42));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        FarmerSideBar.add(jButton8);

        jButton9.setBackground(new java.awt.Color(51, 102, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("My Orders");
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.setPreferredSize(new java.awt.Dimension(200, 42));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        FarmerSideBar.add(jButton9);

        jButton10.setBackground(new java.awt.Color(51, 102, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Logout");
        jButton10.setBorderPainted(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setPreferredSize(new java.awt.Dimension(200, 42));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        FarmerSideBar.add(jButton10);

        FarmerPanel.add(FarmerSideBar, java.awt.BorderLayout.LINE_START);

        FarmerContentArea.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout FarmerContentAreaLayout = new javax.swing.GroupLayout(FarmerContentArea);
        FarmerContentArea.setLayout(FarmerContentAreaLayout);
        FarmerContentAreaLayout.setHorizontalGroup(
            FarmerContentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        FarmerContentAreaLayout.setVerticalGroup(
            FarmerContentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        FarmerPanel.add(FarmerContentArea, java.awt.BorderLayout.CENTER);

        mainCardPanel.add(FarmerPanel, "card4");

        getContentPane().add(mainCardPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void RegisterUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        auth.login(LoginCombo, LoginUsername, LoginPassword);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        CardLayout cl = (CardLayout) authCardPanel.getLayout();
        cl.show(authCardPanel, "card3");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        auth.registerFarmer(RegisterName, RegisterUsername, (JPasswordField) RegisterPassword, RegisterContact);
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    CardLayout cl = (CardLayout) authCardPanel.getLayout();
    cl.show(authCardPanel, "card2");

                        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnManageFarmersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFarmersActionPerformed
        // Remove old content
        ContentArea.removeAll();

        // Create instance of ManageFarmerPanel
        ManageFarmerPanel manageFarmers = new ManageFarmerPanel();

        // Add to content panel
        ContentArea.add(manageFarmers, BorderLayout.CENTER);

        // Refresh panel
        ContentArea.revalidate();
        ContentArea.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageFarmersActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    CardLayout cl = (CardLayout) ContentArea.getLayout();
    cl.show(ContentArea, "card2");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        nav.show("card6");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        nav.show("card6");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrandActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
    saveProductToTable();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
    clearProductFields();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    deleteSelectedProduct();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void deleteSelectedProduct() {
    // 1. Get the table model
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // 2. Get the selected row index
    int selectedRow = jTable1.getSelectedRow();
    
    // 3. Check if a row is actually selected
    if (selectedRow != -1) {
        // Optional: Add a confirmation dialog
        int response = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this product?", 
                "Confirm Deletion", 
                JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            // Remove the row from the model
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Product deleted successfully.");
        }
    } else {
        // If no row is selected, warn the user
        JOptionPane.showMessageDialog(this, 
                "Please select a row from the table to delete.", 
                "No Row Selected", 
                JOptionPane.WARNING_MESSAGE);
    }
}    
    
    private void saveProductToTable() {
    // 1. Validate Inputs
    if (ValidationController.isEmpty(ProductName, "Product Name")) return;
    if (ValidationController.isEmpty(Brand, "Brand")) return;
    if (!ValidationController.isNumeric(Price, "Price")) return;
    if (!ValidationController.isNumeric(Quantity, "Quantity")) return;

    // 2. Get Data
    String name = ProductName.getText().trim();
    String category = comboCategory.getSelectedItem().toString();
    String brandName = Brand.getText().trim();
    String priceVal = Price.getText().trim();
    String qtyVal = Quantity.getText().trim();
    String desc = Description.getText().trim();

    // 3. Add to Table
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{
        name, 
        category, 
        brandName, 
        Double.parseDouble(priceVal), 
        Integer.parseInt(qtyVal), 
        desc
    });

    // 4. Success and Clear
    JOptionPane.showMessageDialog(this, "Product Saved Successfully!");
    clearProductFields();
}

private void clearProductFields() {
    ProductName.setText("");
    Brand.setText("");
    Price.setText("");
    Quantity.setText("");
    Description.setText("");
    comboCategory.setSelectedIndex(0);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel AuthPanel;
    private javax.swing.JTextField Brand;
    private javax.swing.JPanel ContentArea;
    private javax.swing.JTextArea Description;
    private javax.swing.JPanel FarmerContentArea;
    private javax.swing.JPanel FarmerPanel;
    private javax.swing.JPanel FarmerSideBar;
    private javax.swing.JComboBox<String> LoginCombo;
    private javax.swing.JLabel LoginImg;
    private javax.swing.JLabel LoginImg1;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JPanel ManageOrder;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField ProductName;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField RegisterAddress;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField RegisterContact;
    private javax.swing.JTextField RegisterEmail;
    private javax.swing.JTextField RegisterName;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JTextField RegisterPassword;
    private javax.swing.JTextField RegisterUsername;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel authCardPanel;
    private javax.swing.JButton btnManageFarmers;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainCardPanel;
    // End of variables declaration//GEN-END:variables
}
